# Site settings
title: "Radiometria"
email: "matheus.cavalcante@ee.ufcg.edu.br"
description: "Grupo de Pesquisa em Radiometria"
title_image: "assets/logo.png"
baseurl: ""
url: "http://radiometria.github.io"
title_description: "Grupo de Pesquisa em Radiometria da Universidade Federal de Campina Grande"

# Build settings
markdown: kramdown
exclude: [vendor]

collections:
  publicacoes:
    output: false
  membros:
    output: false
    layout: membro
